language: java

addons:
  sonarcloud:
    organization: "germainpinganaud-github"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=pjvilloud_ipi-java-350-ex
